### ISSUE TITLE
Feature: Enable streaming of both accelerometer and gyroscope data

### ISSUE THREAD

**Issue by UteSpiske** [andreped/DSS#20]
Add the ``` Sensors.GYROSCOPE ``` as an aditional sensor when retrieving the data.

**Comment by andreped** [comment]
Added you as collaborator now. Could you see if you are able to set labels and add issue to Project on the right hand side?

**Comment by andreped** [comment]
Fixed in 25a2dade9ff31c12cf92d0ff14f5edccd24672cd
